AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  untitled

  Sample SAM Template for untitled

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  IncBottiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: incbotti/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        IncBotti:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /tg_bot_api
            Method: any
      Environment:
        Variables:
          TELEGRAM_TOKEN: !Ref TelegramToken
Parameters:
  TelegramToken:
    Type: String

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  IncBottiApi:
    Description: "API Gateway endpoint URL for Prod stage for incBotti function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tg_bot_api/"
  IncBottiFunction:
    Description: "Incbotti Lambda Function ARN"
    Value: !GetAtt IncBottiFunction.Arn
  IncBottiFunctionIamRole:
    Description: "Implicit IAM Role created for incBotti function"
    Value: !GetAtt IncBottiFunctionRole.Arn
